package DB_Connection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

//import javax.persistence.Query;
import javax.servlet.http.*;

import com.mysql.jdbc.Statement;

import Model.ReportModel;
import Model.StudentModel;
import DB_Connection.KeyConnection;


public class DB_Connection extends HttpServlet{

	static int i;
	static Connection con = null;
	static String User,Pass,URL;
	
	private static final long serialVersionUID = 1L;

	public static Connection db_connection(){
		Connection con = null;

			try
			{	
											
	 			URL =KeyConnection.URL; 
				User=KeyConnection.User; 
				Pass=KeyConnection.Pass; 

				Class.forName("com.mysql.jdbc.Driver");
				con = DriverManager.getConnection(URL, User,Pass);

			}catch(Exception e)
			{
				
			}

			return con;
	 }

	public static int Report(ReportModel m,String sql) {
		
		
		Connection con = null;
			try
			{	
				URL =KeyConnection.URL; 
				User=KeyConnection.User; 
				Pass=KeyConnection.Pass;

				Class.forName("com.mysql.jdbc.Driver");
				con = DriverManager.getConnection(URL, User,Pass);
			}catch(Exception e)
			{
				
			}
		i=0;
		
		try{
			PreparedStatement ps=con.prepareStatement(sql);
			ps.setString(1, "444");
			ps.setString(2, m.getF_description());
			ps.setString(3, m.getGrammar_score());

			i=ps.executeUpdate();
			
			ps.close();			
			con.close();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
		
		return i;
	}

	public static int StudentRegister(StudentModel m,String query) {
		 int i1=0;
		Connection con=db_connection();
		try{
			PreparedStatement ps=con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
			//connect.prepareStatement("INSERT into employee (time, name) VALUES (?,?)", Statement.RETURN_GENERATED_KEYS);
			
			ps.setString(1, m.getAddress());
			ps.setString(2, m.getBirthDate());
			ps.setLong(3, m.getCarecard());
			ps.setString(4, m.getCity());
			ps.setString(5, m.getDateTime());
			ps.setString(6, m.getDetails());
			ps.setString(7, m.getEmail());
			ps.setLong(8, m.getEmergency());
			ps.setInt(9, m.getFarsiGrade());
			ps.setString(10, m.getFname());
			ps.setString(11, m.getGender());
			ps.setString(12, m.getLname());
			ps.setString(13, m.getPassword());
			ps.setLong(14, m.getPhone());
			ps.setString(15, m.getPostalCode());
			ps.setString(16, m.getRestriction());
			ps.setString(17, m.getUsername());
			
			i1=ps.executeUpdate();
			
			ResultSet tableKeys = ps.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);	
			
			System.out.println("------ "+autoGeneratedID+" --------");
			i1=autoGeneratedID;
			ps.close();			
			con.close();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
		
		return i1;
	}
	
	public static boolean DoubleID(String query) {
		boolean i1=false;
		Connection con=db_connection();
		try{
			PreparedStatement ps=con.prepareStatement(query);
			//connect.prepareStatement("INSERT into employee (time, name) VALUES (?,?)", Statement.RETURN_GENERATED_KEYS);
	
			i1=ps.execute();

			ps.close();			
			con.close();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
		
		return i1;
	}
}
